name: "Terraform Plan"

on:
  pull_request:

env:
  TF_ACTIONS_WORKING_DIR: "./stack"

permissions:
  pull-requests: write

jobs:
  terraform:
    defaults:
      run:
        working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      # so GitHub can check out this repo using the default github.token
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: "Terraform Init"
        run: "terraform init"

      - name: "Terraform Plan"
        run: "terraform plan"
